### PR TITLE
Fix apache2_mod_auth_cas resource for all supported platforms

### LINKED ISSUE #735: Infinite loop from apache2_mod_auth_cas and apache2_module 'auth_cas'  resources
## :ghost: Brief Description

Simply using `apache2_mod_auth_cas 'auth_cas'` results in an infinite loop which eventually causes my `chef-client` run to fail. Sample logging:

```
  * directory[/var/cache/mod_auth_cas/] action create (up to date)
  * apache2_mod_auth_cas[auth_cas] action install
    * file[/etc/httpd/conf.d/auth_cas.conf] action create (skipped due to only_if)
    * apache2_module[auth_cas] action enable
      * apache2_mod_auth_cas[default] action install
        * file[/etc/httpd/conf.d/auth_cas.conf] action create (skipped due to only_if)
        * apache2_module[auth_cas] action enable
          * apache2_mod_auth_cas[default] action install
            * file[/etc/httpd/conf.d/auth_cas.conf] action create (skipped due to only_if)
            * apache2_module[auth_cas] action enable
              * apache2_mod_auth_cas[default] action install
                ...
```

## :pancakes: Cookbook version

```
depends 'apache2', '~> 8.9.1'
```

## :woman_cook:  Chef-Infra Version

```
[~]# chef-client --version
Chef Infra Client: 15.15.1
```

## :tophat: Platform details

Latest AWS Amazon Linux 2 AMI (`ami-0915bcb5fa77e4892`)

## Steps To Reproduce

1. Add the `apache2_mod_auth_cas` resource as-is to a wrapper cookbook
2. Run `chef-client`
3. Notice the infinite loop

## :police_car: Expected behavior

No infinite looping and successful Chef Infra run.

### PR DESCRIPTION
**Pull request by ramereth**
This resolves #735.

- Fix apache devel package name on SUSE platforms
- Fix `libexec_dir` variable in `auth_cas.load` template
- Add Integration tests for `apache2_mod_auth_cas` resource
- Add docs for `apache2_mod_auth_cas`
- Add `:source_checksum`, `:login_url`, `:validate_url` properties to `apache2_mod_auth_cas` resource
- Allow `apache2_mod_auth_cas` resource to be nameless
- Update `mod_auth_cas` source version to 1.2 and other various updates for source installations
- Install `mod_auth_cas` by source on CentOS 8 and SUSE platforms (distro package is not currently available)
- Include yum-epel recipe on RHEL/Amazon platforms

Signed-off-by: Lance Albertson <lance@osuosl.org>

# Description

[Describe what this change achieves]

## Issues Resolved

[List any existing issues this PR resolves]

## Check List

- [ ] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Review by tas50 — DISMISSED** [review]

**Comment by rgriffith** [comment]
@ramereth In-case you are waiting on me, I just wanted to give you a heads up that I'll be out of town about a week so I won't get around to testing this for a bit.

**Comment by ramereth** [comment]
> @ramereth In-case you are waiting on me, I just wanted to give you a heads up that I'll be out of town about a week so I won't get around to testing this for a bit.

Thanks for the heads up. I can wait until you get a chance to look at this. I'd rather get it right.

File: spec/resources/mod_auth_cas_spec.rb [hunk 1]
```diff
@@ -23,6 +23,7 @@
           cache_dir: '/var/cache/apache2',
           login_url: 'https://login.example.org/cas/login',
           validate_url: 'https://login.example.org/cas/serviceValidate',
+          directives: nil,
```
Comment (damacus) [inline spec/resources/mod_auth_cas_spec.rb:26]: An example set of directives would be really helpful here to work this code out.

Comment (ramereth) [reply spec/resources/mod_auth_cas_spec.rb]: @damacus How does the latest addition look?

**Comment by kitchen-porter** [comment]
Released as: [8.10.0](https://github.com/sous-chefs/apache2/releases/tag/8.10.0)
